# Generated by Django 5.0.4 on 2024-04-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('apellido', models.CharField(db_column='Apellido', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colabor', models.IntegerField(db_column='ID_Colabor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('apellido', models.CharField(db_column='Apellido', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'Colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.IntegerField(db_column='ID_Entrada', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
            ],
            options={
                'db_table': 'Entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.IntegerField(db_column='ID_Evento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=500)),
            ],
            options={
                'db_table': 'Evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LugarEvento',
            fields=[
                ('id_lugar_evento', models.IntegerField(db_column='ID_Lugar_Evento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('direccion', models.CharField(db_column='Direccion', max_length=40)),
                ('capacidad', models.IntegerField(db_column='Capacidad')),
            ],
            options={
                'db_table': 'Lugar_Evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id_patrocinador', models.IntegerField(db_column='ID_Patrocinador', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='Nombre_Empresa', max_length=30)),
                ('ruc', models.IntegerField(db_column='RUC')),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'Patrocinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id_promotor', models.IntegerField(db_column='ID_Promotor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('apellido', models.CharField(db_column='Apellido', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'Promotor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id_tipo_entrada', models.IntegerField(db_column='ID_Tipo_Entrada', primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='Categoria', max_length=15)),
                ('precio_entrada', models.FloatField(db_column='Precio_Entrada')),
            ],
            options={
                'db_table': 'Tipo_Entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_cliente', models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='urbanpassApp.cliente')),
                ('valoracion', models.IntegerField(db_column='Valoracion')),
                ('comentario', models.CharField(db_column='Comentario', max_length=300)),
            ],
            options={
                'db_table': 'Valoracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaXClientes',
            fields=[
                ('id_entrada', models.ForeignKey(db_column='ID_Entrada', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='urbanpassApp.entrada')),
            ],
            options={
                'db_table': 'Entrada_X_Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotorXEntrada',
            fields=[
                ('promotor_id_promotor', models.ForeignKey(db_column='Promotor_ID_Promotor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='urbanpassApp.promotor')),
                ('ganancia_promotor', models.FloatField(db_column='Ganancia_Promotor')),
            ],
            options={
                'db_table': 'Promotor_X_Entrada',
                'managed': False,
            },
        ),
    ]
